### PR TITLE
chore(deps): update deps and tailwindcss

### PR DESCRIPTION
**Pull request by vltansky**

### CODE REVIEW

**Comment by nolimits4web** [comment]
- all API tables look off now
- there is something need to be done with `target: 'serverless'` in next config as it complains about it

**Comment by vltansky** [comment]
@nolimits4web take a look now

**Comment by nolimits4web** [comment]
@vltansky
- still issue with Methods and Events tables
- h1 titles have different size with live website
-

**Comment by vltansky** [comment]
@nolimits4web  👀

**Comment by nolimits4web** [comment]
🤞

**Pull request merged**
