### PR TITLE
Fix typo, by default the viewport breakpoints work till some viewport…

### PR DESCRIPTION
**Pull request by the-stas**
… width without inverse param

&gt; changed to &lt;

### CODE REVIEW

**Comment by the-stas** [comment]
Lots of devs a confused when gets those props not working for them
for example, https://stackoverflow.com/a/58207351

**Comment by nolimits4web** [comment]
Thanks, but all correct, in v5 it works like in docs

**Comment by the-stas** [comment]
but for v4.5.0 it is not working...
and folks confused, maybe then we need to have versioning doc or note about prev version.

**Comment by AlimardonO** [comment]
> Thanks, but all correct, in v5 it works like in docs

it's not working for me

**Pull request closed without merging**
