### PR TITLE
prepare mixin for edit link in the API docs

### PR DESCRIPTION
**Pull request by DanielRuf**
Reference: #1

### CODE REVIEW

**Comment by DanielRuf** [comment]
@nolimits4web what do you think? Use `Edit on GitHub` as text?

**Comment by nolimits4web** [comment]
@DanielRuf i'm ok with that. Or maybe like `Improve this Doc`. I see it is just a mixin, so was waiting for further push with this mixin placed somewhere. Should i merge it?

**Comment by DanielRuf** [comment]
Ok. I'll prepare some more commits for this PR to include it into the generated pages.

**Comment by nolimits4web** [comment]
Ok, thanks

**Comment by DanielRuf** [comment]
Done.

**Comment by nolimits4web** [comment]
Thanks

**Pull request merged**
