### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by KSH-code**
It does not exist word in English.

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hello @KSH-code  ,

Can you please make a similar change in this line of this file of another Repo:

https://github.com/nolimits4web/swiper/blob/55f081182b3b9ef1448fa0a0fb66d7668e72192a/src/types/swiper-options.d.ts#L532

I thank you in advance.

**Comment by KSH-code** [comment]
@DAnn2012 
Sure.
After I do it, I mention u.

**Comment by KSH-code** [comment]
https://github.com/nolimits4web/swiper/pull/3782

**Comment by nolimits4web** [comment]
Thanks!

**Pull request merged**
