### PR TITLE
Navigation in demos page (navigation from API)

### PR DESCRIPTION
**Pull request by vltansky**
Hey :)
It's pretty a lot of demos, I was thinking maybe navigation (same one as in API page) would be a nice way to explore demos.
image

### CODE REVIEW

**Comment by vltansky** [comment]
This PR will have a pretty huge conflict with the Stackblitz PR.
If you would like to merge both PR, let me know - I prepared merged branch.

**Comment by nolimits4web** [comment]
Thanks, this is also nice addition, let's prepare common stackblitz + navs demos branch, or i can merge demos and then this one. What do you think?

**Comment by vltansky** [comment]
Didnt understand what you mean

> let's prepare common stackblitz + navs demos branch

Anyway I've updated the PR, resolved the conflict.

**Comment by nolimits4web** [comment]
I pushed some minor tweaks to styling. Merged, thanks 👍

**Pull request merged**
