### PR TITLE
Stackblitz demos

### PR DESCRIPTION
**Pull request by vltansky**
Hi, I've opened today an [issue with proposal](https://github.com/nolimits4web/swiper-website/issues/49) to make demos in stackblitz.
So in this PR I added 15 first demos with link to stackblitz edit. [Example](https://stackblitz.com/edit/swiper-demo-14-centered-slides-auto-slides-per-view?file=index.html)
image
I could do all the demos, but I afraid if you wont approve PR and then it would be just waste of time :)
let me know if you want me to make all other demos.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Hi! Thanks, I will review this on the weekend. Just curios why Stackblitz but not codesandbox for example?

**Comment by vltansky** [comment]
Never heard of codesandbox. Maybe cause I'm an Angular developer...
Angular material, ng-bootstrap & ngx-bootstrap, even ngx-swiper-wrapper have stackblitz demos:)

But if you want I can make the demos in codesandbox.

**Comment by nolimits4web** [comment]
Ok then, no need to move them to codesandbox, was just curious :)

**Comment by vltansky** [comment]
Hi, I added all the demos.
I noticed that not all demos from swiper appear in demo page.
these are missing:
https://github.com/nolimits4web/swiper/blob/master/demos/381-ratio-breakpoints.html
https://github.com/nolimits4web/swiper/blob/master/demos/420-custom-plugin.html
https://github.com/nolimits4web/swiper/blob/master/demos/440-change-direction.html
https://github.com/nolimits4web/swiper/blob/master/demos/450-watchSlidesVisibility.html

Also, I think would be nice to add example usage of importing SCSS/Less, ES modules?

**Comment by nolimits4web** [comment]
Hi! Just reviewed, great job, thanks! So do you want to add those missing demos or should i merge it as it is?

**Comment by vltansky** [comment]
Merge it, I'll make a new PR by the end of the week :)

**Comment by nolimits4web** [comment]
Merged, thanks 👍

**Comment by vltansky** [comment]
I've updated stackblitz demos

**Comment by nolimits4web** [comment]
@vltansky thanks a lot!

**Pull request merged**
