### PR TITLE
Angular docs

### PR DESCRIPTION
**Pull request by vltansky**

### CODE REVIEW

**Comment by vltansky** [comment]
Unable to add Angular code examples:

image

Build fails:
```
[19:18:06] Starting 'pug'...
Starting pug: **/index.pug
[19:18:06] 'pug' errored after 125 ms
[19:18:06] Error in plugin "gulp-pug"
Message:
    D:\projects\swiper-website\src\pug\angular\index.pug:54:5
    52|     import { SwiperModule } from 'src/angular/src/public-api';
    53|
  > 54|     @NgModule({
------------^
    55|       declarations: [AppComponent],
    56|       imports: [BrowserModule, SwiperModule],
    57|       providers: [],

unexpected text "@NgMo"
Details:
    code: PUG:UNEXPECTED_TEXT
    msg: unexpected text "@NgMo"
    line: 54
    column: 5
    filename: D:\projects\swiper-website\src\pug\angular\index.pug
    src: extends ../_internal-template

block vars
  - var title = 'Swiper Angular';
  - var noCenterContent = true;
  - var withLeftNav = true;
```

**Comment by nolimits4web** [comment]
@vltansky It requires indent inside of code block
```
```js
  import ...
```

**Comment by vltansky** [comment]
@nolimits4web omg, thanks. Will continue working on it.

**Comment by vltansky** [comment]
1. Controller and Thumbs are not working in Angular.. So I skipped these sections for now. (will start working on fix)
2. Will be glad for your edition / fixes. I'm not the best writer :)
3. Not sure how "slot props" are called in angular. Maybe context? https://stackoverflow.com/questions/42978082/what-is-let-in-angular-2-templates I've called it `variables` for now.

**Comment by nolimits4web** [comment]
> Will be glad for your edition / fixes. I'm not the best writer :)

Looks good to me, found just one typo, fixed

> Not sure how "slot props" are called in angular. Maybe context? https://stackoverflow.com/questions/42978082/what-is-let-in-angular-2-templates I've called it variables for now.

`variables` sounds fine to me)

**Comment by nolimits4web** [comment]
Merged!

**Pull request merged**
