### PR TITLE
a11y should be enabled by default

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by bitbruder** [comment]
I also think that this option should be more of a "opt-out" than a "opt-in" approach.

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Closing as this is now the default, see https://github.com/nolimits4web/swiper/pull/2490

**Comment by DanielRuf** [comment]
Probably not as the docs are not clear.
At least
> Object with a11y parameters or boolean true to enable with default settings. For example:

**Comment by nolimits4web** [comment]
What is not clear here? :) All defaults there are correct

**Comment by DanielRuf** [comment]
No, the field with the default value is empty in the docs, see my change.

**Comment by DanielRuf** [comment]
Ah, I guess the empty part right from the object / boolean confused me. Sorry for that.

Thanks for creating Swiper 👍

**Pull request closed without merging**
